### ISSUE TITLE
Data Science > Total number of forum posts count were shown incorrect.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/thrive-code#57]
Target URL:

https://www.topcoder.com/thrive/tracks?track=Data%20Science&tax=Data%20Analysis%20%26%20Pattern%20Matching

Steps to Reproduce.

Navigate to the above URL.

1.Observe the count of number of Forum Posts..
2. Count the Forum Posts of the track.
3. Its shown 4 instead of 5.

**Browser:
Refer the articles video

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

![left](https://user-images.githubusercontent.com/4590317/74344187-29113880-4de7-11ea-8997-1dab97562a6a.jpg)

**Comment by kkartunov** [comment]
On left side are categories not posts.
