### ISSUE TITLE
Topcoder_copilot > Total count of articles shown were incorrect.

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/thrive-code#58]
Target URL:

https://www.topcoder.com/thrive/tracks?track=Topcoder&tax=Help%20Articles

Steps to Reproduce.

Navigate to the above URL.

1. Observe the count of number of articles.
2. Count the articles present in the track.
3. It should be 71 but it shows 77 as total count.

**Browser:
[Issue7.zip](https://github.com/topcoder-platform/community-app/files/4169081/Issue7.zip)

** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by kkartunov** [comment]
The count in the banner is the # of assets in that track. Sub categories are different count.
Fixed.
